apiVersion: batch/v1
kind: Job
metadata:
  name: setup-keycloak
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: keycloak-setup
          image: curlimages/curl:latest
            #command: [ "sleep", "10000" ] 
          command: [ "/bin/sh", "-c", "--" ]
          args:
            - >
              curl -sL https://gist.githubusercontent.com/machacekondra/a1f21580858eeb50454b85f138f5bbe4/raw | sh
          env:
            #- name: KEYCLOAK_PASSWORD
            #  valueFrom:
            #    secretKeyRef:
            #      name: "{{ .Values.secretname }}"
            #      key: password
            - name: KEYCLOAK_USER
              value: "user"
            - name: KEYCLOAK_URL
              value: "https://keycloak.apps.templates-cluster.redhat.com"
            - name: REALM_NAME
              value: "master"
            - name: CLIENT_NAME
              value: "backstage"
            - name: REDIRECT_URI
              value: "https://backstage.apps.templates-cluster.redhat.com/oauth2/callback"
            - name: USER_FIRST_NAME
              value: "Ondra"
            - name: USER_LAST_NAME
              value: "LastName"
            - name: USER_EMAIL
              value: "ondra@example.com"
            - name: USER_USERNAME
              value: "ondra"
            - name: USER_PASSWORD
              value: "password"
          imagePullPolicy: IfNotPresent
      restartPolicy: Never
