apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  name: 'np-{{ .Release.Namespace }}-{{ .Release.Name }}'
spec:
  clusterName: {{ .Release.Namespace }}-{{ .Release.Name }}
  replicas: 1
  management:
    autoRepair: false
    upgradeType: InPlace
  platform:
    type: Agent
    agent:
      agentLabelSelector: {}
  release:
    image: quay.io/openshift-release-dev/ocp-release:{{ .Values.ocpVersion }}-x86_64
